In [2]:
import numpy as np

In [3]:
import numpy

In [19]:
print('numpy version',end=" ")
print(np.__version__)

numpy version 1.19.2


In [5]:
a=np.zeros(10)

In [20]:
print("null vector of size 10",a)

null vector of size 10 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
print('memory size= size*itemsize:', a.size*a.itemsize)

memory size= size*itemsize: 80


In [12]:
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [13]:
a=np.zeros(10)

In [14]:
a[4]=1

In [21]:
print('null vector of size 10 but fifth value is 1',a)

null vector of size 10 but fifth value is 1 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
print('vector with values ranging from 10 to 49')
np.arange(10,50)

vector with values ranging from 10 to 49


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
print('Reversing an array using slicing ')
a[::-1]

Reversing an array using slicing 


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [25]:
arr=np.arange(0,9)
arr=arr.reshape(3,3)
print('a 3x3 matrix with values ranging from 0 to 8',arr)

a 3x3 matrix with values ranging from 0 to 8 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
a=np.array([1,2,0,0,4,0])
print('indices of non-zero elements',end=" ")
np.nonzero(a)

indices of non-zero elements 

(array([0, 1, 4], dtype=int64),)

In [27]:
print('identity matrix')
np.eye(3)

identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
print('3x3x3 array with random values')
np.random.randn(3,3,3)

3x3x3 array with random values


array([[[-0.53287642,  0.88148497, -0.13579415],
        [-0.21096224, -0.14329123,  0.69501698],
        [-2.13580505,  1.98174546, -0.24760387]],

       [[-1.10571311,  1.73736261,  0.9144514 ],
        [-0.17243354, -0.80648973,  0.84767294],
        [-1.10992963,  1.47371807,  0.9077202 ]],

       [[ 0.90148535,  0.17030431,  0.20030357],
        [-0.53558139,  0.44112064,  0.01657075],
        [ 1.58852552,  1.45576162,  0.35577888]]])

In [7]:
a=np.random.randn(10,10)
print(a)

[[ 1.04588263e+00 -8.81561572e-01 -8.22695067e-01 -7.54209253e-01
  -6.63490487e-01  4.25618550e-01  2.41819308e-01 -2.27743706e+00
  -4.56373202e-01 -7.22961445e-01]
 [-9.83358846e-01  1.16958415e+00  1.79202912e+00  6.25048790e-01
   3.24924698e-01  2.42386556e-01 -3.75098197e-01  6.66711755e-01
   1.10751436e+00  1.35850982e+00]
 [ 7.64052041e-01  2.42363442e+00 -1.14197397e+00  5.74698531e-01
  -8.53239717e-01 -4.82843780e-02  7.97256553e-01 -1.09952489e+00
   1.87421266e-01 -5.89786412e-01]
 [ 2.94869086e-01 -1.79692125e+00 -2.94955841e+00  4.30040756e-01
   6.27622780e-01  1.71486616e+00 -5.34198529e-01 -6.53749007e-02
   6.46065478e-01  1.06437436e+00]
 [ 2.74207471e-01 -5.52891094e-01 -1.04135597e+00  2.78217311e-01
  -5.97258480e-01 -8.18611188e-01  4.72292952e-01 -9.56766182e-02
  -1.17686116e+00  9.35573712e-01]
 [-7.97381617e-01 -7.56922264e-01 -6.20781642e-01  5.99823614e-02
   5.00254100e-01 -1.11096342e+00 -3.97641539e-01 -4.41950665e-01
  -1.99282297e+00 -4.94809490e-01

In [8]:
print('min-',np.min(a))
print('max-',np.max(a))

min- -2.9495584086786506
max- 2.4236344167606956


In [10]:
b=np.random.randn(30)
print('random vector of size 30 and find the mean value')
print(b)
print(np.mean(b))

random vector of size 30 and find the mean value
[-1.075282   -1.07525294  1.81962018  0.21730089 -0.57805362  1.13807276
 -0.60271171  0.12294479 -0.0637096  -1.36796996  0.73043935 -0.52343964
  1.18713008 -0.53589626  0.24564999  0.08798448  1.47660637  0.13580861
  0.16168954 -0.39065499  0.59306046  0.03583139  0.00195688 -0.14834351
 -0.01637273 -0.55116718  1.8301473   0.32729867 -0.21091463 -0.39163664]
0.0860045437848211


In [11]:
print('2d array with 1 on the border and 0 inside')
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

2d array with 1 on the border and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
print("add a border (filled with 0's) around an existing array")
a=np.ones((5,5))
a=np.pad(a,pad_width=1, mode='constant', constant_values=0)
print(a)

add a border (filled with 0's) around an existing array
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [16]:
a=np.diag(1+np.arange(4),k=-1)
print('5x5 matrix with values 1,2,3,4 just below the diagonal')
print(a)

5x5 matrix with values 1,2,3,4 just below the diagonal
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
a=np.zeros((8,8))
a[::2,::2]=1
a[1::2,1::2]=1
print('8x8 matrix and fill it with a checkerboard pattern')
print(a)

8x8 matrix and fill it with a checkerboard pattern
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [23]:
print('(6,7,8) shape array,index (x,y,z) of the 100th element:')
print(np.unravel_index(99,(6,7,8)))

(6,7,8) shape array,index (x,y,z) of the 100th element
(1, 5, 3)
